package com.kieronquinn.app.smartspacer.plugin.tasker.ui.activities

import com.kieronquinn.app.smartspacer.plugin.tasker.model.SmartspacerComplicationVisibilityTaskerInput

class ComplicationVisibilityActivity: TaskerConfigurationActivity<SmartspacerComplicationVisibilityTaskerInput>()